### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/cloud-bluetooth-devicelink#2]
@janjongboom 

Any chance we could get a docker image of this?

I realize connecting to the bluetooth hardware of a host from within a container may pose issues, but I figured I'd throw this out there since the readme illustrates running this in a VM.

**Comment by janjongboom** [comment]
@loverdeg-ep Forwarding BLE hardware through VMWare does not work, and I don't think it works through VirtualBox either; so I doubt whether this can work.

How I do development is:

* Mbed Edge in Ubuntu VM.
* Devicelink on my Mac, just point it to the IP of the VM.

Pretty straight foward.
